### ISSUE TITLE
Slack invitation link is not valid anymore.

### ISSUE THREAD

**Issue by alishir** [rust-vmm/community#102]
Hi,
I tried to join the slack channel but it seems that the invitation link in the README file is not valid anymore.

**Comment by andreeaflorescu** [comment]
I am trying this one and it seems to be working: https://rust-vmm.slack.com/join/shared_invite/enQtODAxMzA2ODIyMTc2LWRhYjIwZmQ0YzUxODJlMTRhZWU2ZDBjYmJiNzBmOWVmYjg4MjY5YWRjYjM0YzQ5YzgyMTBmYzNlMjMzYmZlODU#/

Are you getting an error with it?

**Comment by alishir** [comment]
Thanks a lot. It works fine.
