### ISSUE TITLE
Decide where to add device implementations (workspace vs separate repo)

### ISSUE THREAD

**Issue by andreeaflorescu** [rust-vmm/community#108]
During the rust-vmm sync meeting on 2021-05-17 (you can find the meeting notes [here](https://etherpad.opendev.org/p/rust-vmm-sync-2021)), we discussed about where to add vhost device implementations. The discussion was triggered by the request to create the [vhost-user-i2c repository](https://github.com/rust-vmm/community/issues/106).

The reason we discussed about having a workspace for vhost devices is that it looks like the emulation code is minimal, and they all will depend on vhost and/or vhost-user-backend. When changes happen in either of the dependencies, it would be easier to just update it in a single PR. This is particularly important if the update is needed because there are breaking changes in the interface of either vhost or vhost-user-backend. If we do not update all the dependencies simultaneously for all vhost-devices, then people won't be able to use the latest versions for all crates, and will need to find the common denominator.

@slp raised some interesting concerns related to this approach. Let's continue the chat here. We can also compile a list of advantages and disadvantages to help us in taking the decision.

**Comment by slp** [comment]
I'm replying to the comment in https://github.com/rust-vmm/community/issues/106#issuecomment-844025779 here:

> Repositories are not necessarily cheap, they have an associated maintenance cost (which is probably hidden for most people). To give a few examples of things you need to do per repository:
> - update the rust-vmm-ci (this one is now taking less time since we switch to dependabot, but people still need to review and update the PRs if needed).
> - in case there are non-default features in a crate, we need to create a private buildkite pipeline and update the Buildkite setup.

Yes, you're right, I forgot about CI.

> The mixed commits is also something that I do not like.

On a second thought, I don't expect vhost-user devices to become very large (except for virtiofsd-rs, which is already on its own repository), so this shouldn't be that bad.

> Packaging the crate **does not** ship all devices. The devices belong to the same workspace, but they each are published individually on crates.io. For example, let's assume that we have the vhost-device
> +workspace with 3 devices in it (vhost-user-i2c, vhost-user-block, vhost-user-net). Then the vhost-device repository will look as follows:
> 
> ```
> /vhost-device
>     Cargo.toml
>     /vhost-user-i2c
>         /src/
>             /src/Cargo.toml
>             /src/lib.rs
>     /vhost-user-block\
>         /src/
>             /src/Cargo.toml
>             /src/lib.rs
>     /vhost-user-network
>         /src/
>             /src/Cargo.toml
>             /src/lib.rs
> ```
> 
> The `Cargo.toml` in the root of the repository is needed such that we can define this repository as a workspace. This will make things like `cargo test` run the tests for all sub-crates in this workspace.
> 
> Running `cargo publish` from the root has no effect. If I am not mistaken it might even yield an error. What must happen when we want to publish a crate is that we need to go to the directory corresponding the
> +crate and run `cargo publish`.

This was my main concern, but seeing that the idea is to use a workspace with multiple crates, it no longer applies.

Thanks for the clarifications, Andreea!

**Comment by vireshk** [comment]
> The reason we discussed about having a workspace for vhost devices is that it looks like the emulation code is minimal, and they all will depend on vhost and/or vhost-user-backend.

FWIW, I am absolutely fine with having a single repo and do feel it is better that way. Please lemme know how should I proceed on this. I am new to the whole rust thing but understand that it is based on pull requests only. So once I have a bare repository, I can base of that and send a pull requrest.

The Linux driver is still to be applied by I2C maintainer, but since the virtio-spec is already updated (https://github.com/oasis-tcs/virtio-spec/commit/f725281ebba7251181c36fdf78d86c6d42fa44eb), I think we don't really need to wait for the kernel code to get merged first. Just trying to pace things a bit here..

**Comment by jiangliu** [comment]
> > The reason we discussed about having a workspace for vhost devices is that it looks like the emulation code is minimal, and they all will depend on vhost and/or vhost-user-backend.
> 
> FWIW, I am absolutely fine with having a single repo and do feel it is better that way. Please lemme know how should I proceed on this. I am new to the whole rust thing but understand that it is based on pull requests only. So once I have a bare repository, I can base of that and send a pull requrest.
> 
> The Linux driver is still to be applied by I2C maintainer, but since the virtio-spec is already updated ([oasis-tcs/virtio-spec@f725281](https://github.com/oasis-tcs/virtio-spec/commit/f725281ebba7251181c36fdf78d86c6d42fa44eb)), I think we don't really need to wait for the kernel code to get merged first. Just trying to pace things a bit here..

@andreeaflorescu @sameo could help to setup the initial repository, then normal PRs for following work.

**Comment by andreeaflorescu** [comment]
@vireshk we're behind with the documentation for our processes. I just started a write up for this here: https://github.com/rust-vmm/community/pull/109.

**Comment by vireshk** [comment]
> @vireshk we're behind with the documentation for our processes. I just started a write up for this here: #109.

Thanks. I hope you will be creating the empty repository though, against which I can send my pull request ?

**Comment by andreeaflorescu** [comment]
> > @vireshk we're behind with the documentation for our processes. I just started a write up for this here: #109.
> 
> Thanks. I hope you will be creating the empty repository though, against which I can send my pull request ?

Yes, I am a bit behind with some other high prio work items. In case @sameo cannot create the repository, I can do that on Tuesday.

**Comment by vireshk** [comment]
Excellent. Thanks @andreeaflorescu

**Comment by andreeaflorescu** [comment]
Since it looks like we are in agreement, I created the vhost-device repository: https://github.com/rust-vmm/vhost-device. I am closing this issue.
