### ISSUE TITLE
Crate Addition Request: Microsoft Hypervisor wrappers

### ISSUE THREAD

**Issue by russell-islam** [rust-vmm/community#110]
## Crate Name
mshv-{bindings,ioctls}
## Short Description
These two creates will be under a workspace named as MSHV and these crates are similar to kvm-{bindinmgs,ioctls). These crates will provide the APIs and definitions to create a VMM on Microsoft Hypervisor along with other rust-vmm creates.
reposity pattern should be as follow.
`
mshv ----|----------mshv-bindings
               |
               |-----------mshv-ioctls
               |-----------Cargo.toml
               |-----------CI

`
## Why is this crate relevant to the rust-vmm project?
As these craetes are already working with another rust-vmm based VMM which is Cloud Hypervisor, it is wise to let others to play around it and integrate it with their VMM.

All the functionalities and APIs are already implemented to create a bare minimal VM using cloud hypervisor. Here is the link of the repository currently residing in cloud-hypervisor project.
https://github.com/cloud-hypervisor/mshv

**Comment by andreeaflorescu** [comment]
Since we already discussed about this at the sync meeting, I'll go ahead and create the repository. All repositories are created from the crate-template, and that is targeted to individual crates. There will be a few updates needed to convert it to a workspace.

If you need help, please let us know.

**Comment by russell-islam** [comment]
> Since we already discussed about this at the sync meeting, I'll go ahead and create the repository. All repositories are created from the crate-template, and that is targeted to individual crates. There will be a few updates needed to convert it to a workspace.
> 
> If you need help, please let us know.

Thanks for the response. Since the crates are already in working condition with Cloud Hypervisor do think I can keep all the previous commits while I move the code here. I can make workspace and folder structure done in initial commits then cherry-pick the commits.

**Comment by andreeaflorescu** [comment]
@russell-islam sounds good. Can you open a PR with them?

**Comment by russell-islam** [comment]
> @russell-islam sounds good. Can you open a PR with them?

PR: https://github.com/rust-vmm/mshv/pull/2

**Comment by andreeaflorescu** [comment]
We can close this issue and move the conversation on the PR.
