### ISSUE TITLE
Crate Addition Request: acpi_tables

### ISSUE THREAD

**Issue by rbradford** [rust-vmm/community#138]
## Crate Name

acpi_tables

## Short Description

Adds support for some static ACPI tables and AML generate for DSDT

## Why is this crate relevant to the rust-vmm project?

Used by the Cloud Hypervisor project and has been copied into CrosVM. It would be useful for any VMM that wants to use ACPI for driving functionality such as device, CPU or memory hotplug.

**Comment by andreeaflorescu** [comment]
@rbradford do we envision having multiple crates in an "acpi" workspace? I am wondering if we should create this as "acpi" and just have "acpi_tables" as a crate in the workspace.

**Comment by andreeaflorescu** [comment]
I created the repo: https://github.com/rust-vmm/acpi_tables

**Comment by aghecenco** [comment]
Crate's up and nearly running.

**Comment by rbradford** [comment]
@aghecenco @andreeaflorescu Thank you both!
