### ISSUE TITLE
Update community readme

### ISSUE THREAD

**Issue by andreeaflorescu** [rust-vmm/community#15]
We should specify in the readme what rust-vmm is.

**Comment by hannibalhuang** [comment]
anyone working on this one ? It would be really helpful to have an introduction document with architecture diagram

**Comment by andreeaflorescu** [comment]
Hey @hannibalhuang I will start working on this. Sorry for the long wait! In the meantime, you can read an introduction about rust-vmm here: https://opensource.com/article/19/3/rust-virtual-machine

**Comment by hannibalhuang** [comment]
> Hey @hannibalhuang I will start working on this. Sorry for the long wait! In the meantime, you can read an introduction about rust-vmm here: https://opensource.com/article/19/3/rust-virtual-machine

No problem :)

**Comment by andreeaflorescu** [comment]
PR merged: #59
