### ISSUE TITLE
Missing crate owners for `vhost-device-vsock`

### ISSUE THREAD

**Issue by epilys** [rust-vmm/community#169]
Running my [`check_owners.sh`](https://gist.github.com/epilys/b8d390f66d6f47dbbf681df85b23af68) script, I get:

```text
vhost-device-vsock
INFO: querying https://crates.io/api/v1/crates/vhost-device-vsock/owners
INFO: API reply was {"users":[{"avatar":"https://avatars.githubusercontent.com/u/16856679?v=4","id":79784,"kind":"user","login":"JonathanWoollett-Light","name":"Jonathan Woollett-Light","url":"https://github.com/JonathanWoollett-Light"},{"avatar":"https://avatars.githubusercontent.com/u/6713874?v=4","id":92595,"kind":"user","login":"stefano-garzarella","name":"Stefano Garzarella","url":"https://github.com/stefano-garzarella"},{"avatar":"https://avatars.githubusercontent.com/u/571355?v=4","id":155147,"kind":"user","login":"mathieupoirier","name":"Mathieu Poirier","url":"https://github.com/mathieupoirier"},{"avatar":"https://avatars.githubusercontent.com/u/12929622?v=4","id":216541,"kind":"user","login":"vireshk","name":"Viresh Kumar","url":"https://github.com/vireshk"},{"avatar":"https://avatars.githubusercontent.com/u/46028664?v=4","id":1481,"kind":"team","login":"github:rust-vmm:gatekeepers","name":"gatekeepers","url":"https://github.com/rust-vmm"}]}
OK: rust-vmm:gatekeepers is an owner.
ERROR: stsquad is not an owner.
OK: vireshk is an owner.
OK: stefano-garzarella is an owner.
ERROR: epilys is not an owner.
```

@vireshk, @stefano-garzarella  you need to exec:

```shell
cargo owner --add stsquad vhost-device-vsock ;
cargo owner --add epilys vhost-device-vsock
```

**Comment by vireshk** [comment]
Hmm, I can do it, sure.
I should be running this for all maintainers of vhost-device wrokspace ?

@stefano-garzarella @stsquad  ?

**Comment by epilys** [comment]
@vireshk I have opened separate issues for other vhost-device crates, just run the cargo owner commands in each issue and it will be enough

**Comment by vireshk** [comment]
Yeah, I have seen that. But I don't see names of all four of us in the examles, or by owners of the crates (in the sense of contributors) and so want to clarify all these details here first.

**Comment by epilys** [comment]
What examples are you referring to?

**Comment by vireshk** [comment]
I didn't realize earlier that the issues are created in the rust-vmm community, I thought it is vhost-device only :)

Like you have mentioned these for `vhost-device-gpio`:

```
cargo owner --add stsquad vhost-device-gpio ;
cargo owner --add epilys vhost-device-gpio
```

This doesn't have myself, Erik or Stefano. I am not sure who all should be owners there.

**Comment by Ablu** [comment]
> This doesn't have myself, Erik or Stefano. I am not sure who all should be owners there.

I am not a OWNER of any rust-vmm component at the moment, so I should not have access. Stefano already has access: https://crates.io/crates/vhost-device-gpio

**Comment by epilys** [comment]
The list of owners is in the issue content I posted above!

@vireshk the motivation was this doc: 

https://github.com/rust-vmm/community/blob/main/MAINTAINERS.md#becoming-a-repository-maintainer

It says that both the gatekeeper team and CODEOWNERS must be owners of publishable crates on crates.io. That's all

You are already in the owners list, like the issue says.

**Comment by vireshk** [comment]
> It says that both the gatekeeper team and CODEOWNERS must be owners of publishable crates on crates.io. That's all
> 
> You are already in the owners list, like the issue says.

Ahh, that's what I was missing. So we are only trying to add the missing ones. Sound good. Thanks.

**Comment by stefano-garzarella** [comment]
```
$ cargo owner --add stsquad vhost-device-vsock ;
cargo owner --add epilys vhost-device-vsock
    Updating crates.io index
       Owner user stsquad has been invited to be an owner of crate vhost-device-vsock
    Updating crates.io index
       Owner user epilys has been invited to be an owner of crate vhost-device-vsock
```
