### ISSUE TITLE
Missing crate owners for `vm-memory`

### ISSUE THREAD

**Issue by epilys** [rust-vmm/community#170]
Running my [`check_owners.sh`](https://gist.github.com/epilys/b8d390f66d6f47dbbf681df85b23af68) script, I get:

```
vm-memory
INFO: querying https://crates.io/api/v1/crates/vm-memory/owners
INFO: API reply was {"users":[{"avatar":"https://avatars.githubusercontent.com/u/2815944?v=4","id":37110,"kind":"user","login":"andreeaflorescu","name":"Andreea Florescu","url":"https://github.com/andreeaflorescu"},{"avatar":"https://avatars.githubusercontent.com/u/46103760?v=4","id":99643,"kind":"user","login":"lauralt","name":"Laura Loghin","url":"https://github.com/lauralt"},{"avatar":"https://avatars.githubusercontent.com/u/115481277?v=4","id":186043,"kind":"user","login":"roypat","name":"Patrick Roy","url":"https://github.com/roypat"},{"avatar":"https://avatars.githubusercontent.com/u/46028664?v=4","id":1481,"kind":"team","login":"github:rust-vmm:gatekeepers","name":"gatekeepers","url":"https://github.com/rust-vmm"}]}
OK: rust-vmm:gatekeepers is an owner.
ERROR: alexandruag is not an owner.
ERROR: bonzini is not an owner.
ERROR: jiangliu is not an owner.
ERROR: tkreuzer is not an owner.
OK: roypat is an owner.
Missing crate owners for vm-memory, please add them.
```

@roypat, you need to exec:

```shell
cargo owner --add alexandruag vm-memory ;
cargo owner --add bonzini vm-memory ;
cargo owner --add jiangliu vm-memory ;
cargo owner --add tkreuzer vm-memory
```

**Comment by roypat** [comment]
> Running my [`check_owners.sh`](https://gist.github.com/epilys/b8d390f66d6f47dbbf681df85b23af68) script, I get:
> 
> ```
> vm-memory
> INFO: querying https://crates.io/api/v1/crates/vm-memory/owners
> INFO: API reply was {"users":[{"avatar":"https://avatars.githubusercontent.com/u/2815944?v=4","id":37110,"kind":"user","login":"andreeaflorescu","name":"Andreea Florescu","url":"https://github.com/andreeaflorescu"},{"avatar":"https://avatars.githubusercontent.com/u/46103760?v=4","id":99643,"kind":"user","login":"lauralt","name":"Laura Loghin","url":"https://github.com/lauralt"},{"avatar":"https://avatars.githubusercontent.com/u/115481277?v=4","id":186043,"kind":"user","login":"roypat","name":"Patrick Roy","url":"https://github.com/roypat"},{"avatar":"https://avatars.githubusercontent.com/u/46028664?v=4","id":1481,"kind":"team","login":"github:rust-vmm:gatekeepers","name":"gatekeepers","url":"https://github.com/rust-vmm"}]}
> OK: rust-vmm:gatekeepers is an owner.
> ERROR: alexandruag is not an owner.
> ERROR: bonzini is not an owner.
> ERROR: jiangliu is not an owner.
> ERROR: tkreuzer is not an owner.
> OK: roypat is an owner.
> Missing crate owners for vm-memory, please add them.
> ```
> 
> @roypat, you need to exec:
> 
> ```shell
> cargo owner --add alexandruag vm-memory ;
> cargo owner --add bonzini vm-memory ;
> cargo owner --add jiangliu vm-memory ;
> cargo owner --add tkreuzer vm-memory
> ```

It seems that bonzini and tkreuzer dont have crates.io accounts, so I couldnt invite them :(

**Comment by epilys** [comment]
@roypat crates.io uses github accounts only, they probably have never logged in to crates.io. We can skip the missing handles for the time being, no problem.
