### ISSUE TITLE
Crate Addition Request: vhost

### ISSUE THREAD

**Issue by jiangliu** [rust-vmm/community#20]
## Crate Name
vhost or vhost_rs

## Short Description
The crate would provide:
- A Vhost trait
- A VhostUserMaster trait for vhost-user master endpoints
- A VhostUserSlave trait for vhost-user slave endpoints
- An implementation of the Vhost trait based on linux kernel vhost drivers
- An implementation of the Vhost trait based on the vhost-user protocol
- An implementation of the VhostUserMaster trait

## Why is this crate relevant to the rust-vmm project?
The vhost crate may be used to implement virtio device backends.

**Comment by andreeaflorescu** [comment]
If vhost is available, we can use vhost. Although I wouldn't name it vhost if we plan to add other backends there as well.

**Comment by jiangliu** [comment]
vhost is still available currently. 
Any better suggestions?
@sboeuf @dagrh

**Comment by sameo** [comment]
`vhost-backend` ?

**Comment by andreeaflorescu** [comment]
Are we going to have only vhost based backends there? I am not sure what would be the better separation of concerns in this case.

**Comment by sboeuf** [comment]
@jiangliu as discussed earlier, the whole architecture sounds good to me, but do we want everything in one single crate? Or do we want each implementation (vhost-kernel, vhost-user) of the vhost trait to be into separate crates?

**Comment by jiangliu** [comment]
How about one crate with rust features for vhost-kern, vhost-user-master and vhost-user-slave? Otherwise we may have too many crates under the rust-vmm project.

**Comment by sameo** [comment]
If we can manage that with features, I think it would make more sense to have one single crate.

**Comment by andreeaflorescu** [comment]
One crate for vhost related backends (user, slave, kernel) and another one miscellaneous :))?

**Comment by jiangliu** [comment]
I think the vhost crate should aim to build the bridge between the virtio-devices crate and vhost backend drivers, such as vhost-vsock, dpdk-ovs and spdk etc. It shouldn’t focus on implementing vhost backend drivers.

**Comment by sameo** [comment]
> I think the vhost crate should aim to build the bridge between the virtio-devices crate and vhost backend drivers, such as vhost-vsock, dpdk-ovs and spdk etc. It shouldn’t focus on implementing vhost backend drivers.

Agreed. This is a crate that we will use to set the vmm virtio devices **vhost** backend endpoint, be it in kernel (vhost) or in userspace (vhost-user). The actual backend is not going to be part of this crate.

So to summarize: `vhost` as a name is fine with me.

**Comment by sboeuf** [comment]
Sounds good to me :+1:

**Comment by sboeuf** [comment]
LGTM

@sameo @andreeaflorescu @zachreizner @aghecenco PTAL

**Comment by andreeaflorescu** [comment]
Lgtm as well.

**Comment by sameo** [comment]
https://github.com/rust-vmm/vhost created, closing that issue.
