### ISSUE TITLE
Crate Addition: kvm-ioctls

### ISSUE THREAD

**Issue by andreeaflorescu** [rust-vmm/community#21]
## Crate Name: kvm-ioctls

The `kvm` name is taken. The proposal is to use `kvm-ioctls` instead.

## Short Description
The `kvm-ioctls` crate will offer wrappers over the KVM ioctls.
KVM ioctls are of three types:
- system ioctls -> grouped in the implementation of the `Kvm` structure
- VM ioctls-> grouped in the implementation of the `Vm` structure
- vCPU ioctls -> grouped in the implementation of the `Vcpu` structure

## Why is this crate relevant to the rust-vmm project?
We need some wrappers for opening `dev/kvm`, creating VMs, creating vCPUs & so on.

**Comment by sameo** [comment]
LGTM

**Comment by aghecenco** [comment]
LGTM

**Comment by jiangliu** [comment]
LGTM

**Comment by sboeuf** [comment]
LGTM

**Comment by sameo** [comment]
@andreeaflorescu Repo created at rust-vmm/kvm-ioctls. I'm closing that issue now.
