### ISSUE TITLE
Crate Addition Request: linux-loader

### ISSUE THREAD

**Issue by sameo** [rust-vmm/community#24]
## Crate Name

`linux-loader`

## Short Description

* Parsing and loading vmlinux (raw ELF image) and bzImage images
* Linux command line parsing and generation
* Definitions and helpers for the Linux boot protocol, multiboot and PVH headers.

## Why is this crate relevant to the rust-vmm project?

Direct kernel boot but this could also be consumed by e.g. rust written bootloaders.

**Comment by jiangliu** [comment]
Will the loader parse ELF sections? Or will it only parse ELF program headers?

**Comment by bonzini** [comment]
This should also include structs and builders for the Linux boot protocol header (https://www.kernel.org/doc/Documentation/x86/boot.txt), multiboot header, PVH header.

**Comment by sameo** [comment]
> Will the loader parse ELF sections? Or will it only parse ELF program headers?

Only ELF program headers.

**Comment by sameo** [comment]
> This should also include structs and builders for the Linux boot protocol header (https://www.kernel.org/doc/Documentation/x86/boot.txt), multiboot header, PVH header.

Indeed, yes.

**Comment by andreeaflorescu** [comment]
There are lots of people asking for bzimage support in Firecracker. Would this be a good crate for adding such support as well?

**Comment by bonzini** [comment]
Yes, it would be exactly the place to provide the support code and
especially data structures for that!

Il lun 18 feb 2019, 18:13 Andreea Florescu <notifications@github.com> ha
scritto:

**Comment by andreeaflorescu** [comment]
@bonzini totally irrelevant to the conversation, but I find it funny that you have you email client (maybe) in Italian 😂

**Comment by sameo** [comment]
Edited the crate description according to the comments.

**Comment by sameo** [comment]
@andreeaflorescu @bonzini Are we ok with creating this crate? I'd like to move forward with that one.

**Comment by andreeaflorescu** [comment]
Yap, sounds good.

**Comment by bonzini** [comment]
Of course.

**Comment by sameo** [comment]
Repo created, I'm closing that one.
