### ISSUE TITLE
Crate Addition Request: libc-utils

### ISSUE THREAD

**Issue by sameo** [rust-vmm/community#28]
## Crate Name

`libc-utils`

## Short Description

A collection of modules that essentially provide helpers and utilities on top of the `libc` crate:

* `errno`
* `fork`
* `poll`
* `signal`
* `ioctl`
* `timerfd`
* `eventfd`
* `syslog`
* `terminal`

## Why is this crate relevant to the rust-vmm project?

Although this crate could be used by many projects not related to VMMs or virtualization at all, this set of tools and helpers make writing a VMM easier and shorter than using the `libc` crate directly.

**Comment by jiangliu** [comment]
How about adding support of memfd?

**Comment by sameo** [comment]
@jiangliu memfd would belong there as well

**Comment by dagrh** [comment]
* Samuel Ortiz (notifications@github.com) wrote:
> ## Crate Name
> 
> `libc-utils`
> 
> ## Short Description
> 
> A collection of modules that essentially provide helpers and utilities on top of the `libc` crate:
> 
> * `errno`
> * `fork`
> * `poll`
> * `signal`
> * `ioctl`
> * `timerfd`
> * `eventfd`
> * `syslog`
> * `terminal`
> 
> ## Why is this crate relevant to the rust-vmm project?
> 
> Although this crate could be used by many projects not related to VMMs or virtualization at all, this set of tools and helpers make writing a VMM easier and shorter than using the `libc` crate directly.

Doesn't the nix crate have this stuff already?

IMHO if it's general stuff then we should contribute to the
libc/nix/whatever crates as needed rather than spinning our own.

Dave

> 
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/rust-vmm/community/issues/28
--
Dr. David Alan Gilbert / dgilbert@redhat.com / Manchester, UK

**Comment by sameo** [comment]
> > * Samuel Ortiz (notifications@github.com) wrote:
> > Although this crate could be used by many projects not related to VMMs or virtualization at all, this set of tools and helpers make writing a VMM easier and shorter than using the `libc` crate directly.

> Doesn't the nix crate have this stuff already? IMHO if it's general stuff then we should contribute to the libc/nix/whatever crates as needed rather than spinning our own. 

After looking at `nix`, I think in some cases it does have roughly what we need, in other cases it does not. Overall, I find this crate to be very large and in some cases complex for what we're trying to achieve. We need a small subset of `nix` and I feel this is a case where we may prefer to have our own smaller implementation than add one more, fairly large dependency.

**Comment by liujing2** [comment]
@sameo fork might only be created by crosvm now, and I found all the functions in fork.rs are not used, expect the #[test] inside. Do we still need fork crate?

**Comment by sameo** [comment]
@liujing2 If neither crosvm nor FC use it, then we should not add it for now.

**Comment by sameo** [comment]
During last week's (03/06) call, we had a discussion as to whether we want to split `sys_utils` into logically separated crates or not.
The split might cause more issues than advantages, so we may want to start with one single crate, on a single repo, and eventually separate it into finer grain crates (Still from one single repo) if there's an actual reason to do so. However I propose we use a less generic name than `sys_utils`, something like `vmm_sys_utils`.

@andreeaflorescu @zachreizner wdyt?

**Comment by zachreizner** [comment]
A single crate would be the least risky option in my opinion.
As far as naming goes, I think `sys_util` (with or without `s`) is fine. The only truly vmm specific parts (`kvm`, `kvm-sys`) are part of a different crate already. On the other hand, prefixing all our crates with `vmm_` does give our crates a certain cohesiveness that could be appealing. For example, it's clear all the `gfx_` crates are from the same group and are designed to work together.

**Comment by andreeaflorescu** [comment]
I am having serious difficulties in naming that crate or providing any feedback for the name because I think it does a lot of things. So any name is fine with me.

But I would insist on not publishing it to crates.io unless we truly need to because we cannot for example publish the `virtio-devices` crate as it will depend on it.

**Comment by sameo** [comment]
> On the other hand, prefixing all our crates with vmm_ does give our crates a certain cohesiveness 

I agree. And that's the main reason why I was proposing this prefix. As you said there's nothing vmm specific in this crate.

**Comment by sameo** [comment]
@andreeaflorescu 

> But I would insist on not publishing it to crates.io unless we truly need to because we cannot for example publish the virtio-devices crate as it will depend on it.

The `devices` and `virtio-devices` crates only need `sys_util` for the `EventFd` implementation. The `linux-loader` crate will need it for the `struct_util` wrapper, but since it's the only user of that part of `sys_util` we should probably move it to `linux_loader` instead.

So we may be able to live without publishing it to crates.io in the short term.

**Comment by jiangliu** [comment]
The vhost crate plans to replace nix crate with sys_utils, which uses Unix Domain Socket to pass file descriptor among processes.

**Comment by sameo** [comment]
> So could we add sock_ctrl_msg.rs to the sys_util crate?

@liujing2 Could we please do that?

**Comment by sameo** [comment]
@zachreizner @andreeaflorescu @jiangliu I'd like to go ahead and create a `vmm-sys-util` repo to host this crate. It seems we have some sort of agreement on having one crate at least.
Any last minute disagreement?

**Comment by liujing2** [comment]
@sameo  Sure, I'll take a look later.

**Comment by andreeaflorescu** [comment]
I guess we can go ahead and create the repository. There's no reason to block on this. We can rename it later if needed.

**Comment by sameo** [comment]
@andreeaflorescu @zachreizner vmm-sys-util is created.

@liujing2 Could you please send your initial PR against that new repo?

**Comment by liujing2** [comment]
@sameo No problem. Let me send it from my repo.

**Comment by sameo** [comment]
vmm-sys-utils is created. I'm closing that one.
