### ISSUE TITLE
Repository/Crate Review Request

### ISSUE THREAD

**Issue by andreeaflorescu** [rust-vmm/community#4]
### Repository Path
https://github.com/andreeaflorescu/kvm-bindings
### Short Description
Feature-wise this is a copy of [kvm_wrapper](https://github.com/rust-vmm/kvm_wrapper). The crate is now named kvm-bindings as the `-bindings` suffix seems to be commonly used for crates that export Rust FFI bindings.
### Notes
Travis CI is not enabled for this repository, but I will add it once we move it rust-vmm.
After the review process, I will also publish the kvm-bindings crate and update the kvm_wrapper as follows:
- publish a new version for `kvm_wrapper` on crates.io with an updated readme in which I'll specify that kvm_wrapper is obsolete and people should use kvm-bindings instead.
- [Yank](https://doc.rust-lang.org/cargo/reference/publishing.html#managing-a-cratesio-based-crate) all current versions of the `kvm_wrapper` crate.

**Comment by aghecenco** [comment]
LGTM :+1:

**Comment by aghecenco** [comment]
Can you add the nifty crates.io badge thingy for kvm-bindings? It's a bit late for kvm-wrapper as it's almost out the door.

Code snippet for README.md:

```
[![Crates.io](https://img.shields.io/crates/v/kvm-bindings.svg)](https://crates.io/crates/kvm-bindingsw)
```

Result:

[![Crates.io](https://img.shields.io/crates/v/kvm-bindings.svg)](https://crates.io/crates/kvm-bindingsw)

**Comment by dgreid** [comment]
LGTM too, we'll try to use 'bindings' consistently moving forward.

**Comment by andreeaflorescu** [comment]
I'll go ahead and move the repository to rust-vmm. If people have more comments I can address them and create a new release.

**Comment by andreeaflorescu** [comment]
Published to [crates.io](https://crates.io/crates/kvm-bindings)
