### ISSUE TITLE
Repository Addition Request - rust-vmm-dev-container

### ISSUE THREAD

**Issue by andreeaflorescu** [rust-vmm/community#42]
## Short Description
Container with all dependencies required for running integration tests for the rust-vmm crate.

## Why is this crate relevant to the rust-vmm project?
- Deploy it as part of our CI to manage dependencies across multiple platforms
- It can also be used for development to test the code before submitting PRs in the same environment that it is going to be tested as part of the CI.
- You can already find the Dockerfile [here](http://github.com/andreeaflorescu/rust-vmm-dev-container).

P.S. I already published it on docker hub under the name [rust-vmm-dev](https://cloud.docker.com/repository/docker/fandree/rust-vmm-dev) so I can run my experiments with [buildkite](https://buildkite.com/rust-vmm/kvm-ioctls-ci/builds/36).

We can create a rust-vmm organization on docker hub and push the container there.

**Comment by sameo** [comment]
@Andreea I think it would make a lot of sense to host it in rust-vmm. Maybe we could have a more generic name for that repo like e.g. `dev-tools` instead?

**Comment by andreeaflorescu** [comment]
Do we want to add more tools there (other than the container stuff)? We also have to find a host for the yaml configuration file (if we end up using builkite).

**Comment by sameo** [comment]
I'm pretty sure we'll end up putting more tooling there. Better that than having to rename it afterwards.

**Comment by andreeaflorescu** [comment]
I kinda like the model where you have the docker related documentation and files in one repository and then link it to Docker Hub.
Checkout how kcov is handling this: https://hub.docker.com/r/ragnaroek/kcov/

I am inclined towards 2 repositories:
- rust-vmm-container (or something like that) which contains the Dockerfile and documentation
- some other repository for integration tests configuration (this can be the yaml file in case we are going to go with Buildkite) and other tools that we will need for rust-vmm

**Comment by sameo** [comment]
If you prefer a dedicated repo, I'm fine with that.
Could we name it `dep-container` or something like that? `github.com/rust-vmm/rust-vmm-container` stutters a bit...

**Comment by sameo** [comment]
@andreeaflorescu Let's create the rust-vmm-container repo.

**Comment by andreeaflorescu** [comment]
@sameo done. Will add a PR soon.
