### ISSUE TITLE
Access Request to rust-vmm/vm-memory

### ISSUE THREAD

**Issue by bonzini** [rust-vmm/community#44]
GitHub Username: bonzini

I would like to be able to close issues, assign them to myself etc.

**Comment by sameo** [comment]
@bonzini You already have write access to the `vm-memory` repo. Do you confirm you don't have permissions to close issues?

**Comment by bonzini** [comment]
I don't; I also don't have permissions to assign issues to myself, set up labels etc.

**Comment by sameo** [comment]
You're an admin of that repo now. Could you try again, please?

**Comment by andreeaflorescu** [comment]
I added the required permissions one hour ago and I forgot to update the issue. Did you check again?

**Comment by bonzini** [comment]
It works! Thanks
