### ISSUE TITLE
How do join the rust-vmm slack?

### ISSUE THREAD

**Issue by caniszczyk** [rust-vmm/community#53]
id: caniszczyk@linuxfoundation.org

**Comment by jbryce** [comment]
https://join.slack.com/t/rust-vmm/shared_invite/enQtNTI3NDM2NjA5MzMzLTJiZjUxOGEwMTJkZDVkYTcxYjhjMWU3YzVhOGQ0M2Y5NmU5MzExMjg5NGE3NjlmNzNhZDlhMmY4ZjVhYTQ4ZmQ

**Comment by kapilt** [comment]
is there a reason there isn't a readme reference to this?  atm its only discoverable via searching the GitHub org `slack` most public references are to the mailing list and meeting minutes..

**Comment by andreeaflorescu** [comment]
Not really, I think we have a permanent link to join the slack community. I'll add an issue to update the readme with this information.
