### ISSUE TITLE
Crate Addition Request: vfio

### ISSUE THREAD

**Issue by sameo** [rust-vmm/community#57]
## Crate Name

`vfio`

## Short Description

The `vfio` crate would allow for rust-vmm based VMMs to assign host devices/functions to the guest workload. 

## Why is this crate relevant to the rust-vmm project?

Mostly for implementing direct device assignment.

**Comment by zhenyw** [comment]
Hi, we're working on adding VFIO support for crosvm: https://chromium-review.googlesource.com/c/chromiumos/platform/crosvm/+/1580455/1.

The original purpose is for VFIO mdev support on virtual GPU acceleration, and we're evaluating for general VFIO passthrough too. We hope to add vfio support for rust-vmm based on that work.

thanks

**Comment by sameo** [comment]
@andreeaflorescu @raduweiss Given the reference to device passthrough in the [latest Firecracker update](https://aws.amazon.com/blogs/opensource/firecracker-open-source-update-may-2019/), are you planning to use VFIO as well?

**Comment by andreeaflorescu** [comment]
@sameo We didn't scope the GPU support in Firecracker just yet and we don't know what the final solution will be there, so I don't think we can answer your question just yet.

**Comment by chao-p** [comment]
Instead of having one crate to cover everything, I believe it's more useful to split this into several crates. I added vfio-bindings(#74) and vfio-ioctls(#75) which seems quite clear now. Other crate like vfio-pci may be added later when necessary.

**Comment by sameo** [comment]
We can close that one now, we have the vfio-ioctls and vfio-bindings crates.
