### ISSUE TITLE
Repository Addition Request - Repository Template

### ISSUE THREAD

**Issue by andreeaflorescu** [rust-vmm/community#64]
## Short Description
Proposed repository template here:  https://github.com/andreeaflorescu/rust-vmm-repo-template

The template is still WIP because I didn't give it much thought, so I will probably update it.
GitHub blogpost about repository templates: https://github.blog/2019-06-06-generate-new-repositories-with-repository-templates/

## Why is this crate relevant to the rust-vmm project?
This repository will be a template for all repositories added to rust-vmm. This should speed up creating new projects in rust-vmm.

**Comment by jiangliu** [comment]
Could we also add Apache2 license files to the template?

**Comment by andreeaflorescu** [comment]
@jiangliu yap, adding it.

**Comment by sameo** [comment]
> Could we also add Apache2 license files to the template?

And the BSD-3 Clause one.

**Comment by sameo** [comment]
This makes a lot of sense to me.

**Comment by andreeaflorescu** [comment]
@sameo about the BSD-3 Clause one: for code that's new and not coming from CrosVM is the BSD-3 clause one required? I would like to better understand this. Probably will drop an email to the rust-vmm email list as well.

I was thinking that for code that comes from CrosVM we need to have Apache + BSD 3 clause, but for code from Firecracker/new code can we have Apache + MIT instead?

**Comment by andreeaflorescu** [comment]
BTW, let's first decide if we want a template. We can then create an empty repository and add the template as the first PR. We can comment on the PR on other things we should add to the template.

**Comment by jiangliu** [comment]
This is must-to-have repo:)

**Comment by andreeaflorescu** [comment]
Should we name this repository `crate-template` as it is going to be used only for repositories that are crates?

**Comment by sameo** [comment]
This LGTM, let's do it.

**Comment by sameo** [comment]
`crate-template` sounds fine to me.

**Comment by andreeaflorescu** [comment]
Created repo: https://github.com/rust-vmm/crate-template
