### ISSUE TITLE
Crate Addition Request: vfio-bindings

### ISSUE THREAD

**Issue by chao-p** [rust-vmm/community#74]
## Crate Name
vfio-bindings

## Short Description
Rust FFI bindings to Linux VFIO(Virtual Function I/O) generated using bindgen. 

## Why is this crate relevant to the rust-vmm project?
Like kvm-bindings, the crate provides basic VFIO 'raw' system control interfaces.

**Comment by chao-p** [comment]
We already implemented this in cloud-hypervisor(https://github.com/intel/cloud-hypervisor/tree/master/vfio-bindings) and want to push it to rust-vmm.

**Comment by jiangliu** [comment]
Is there any difference between linux 4.19 and 5.0 for the VFIO subsystem?

**Comment by sameo** [comment]
Done, closing that issue.
