### ISSUE TITLE
Crate Addition Request: vfio-ioctls

### ISSUE THREAD

**Issue by chao-p** [rust-vmm/community#75]
## Crate Name
vfio-ioctls

## Short Description
The crate provides safe wrappers over the VFIO API that generated in vfio-binding(#74).

## Why is this crate relevant to the rust-vmm project?
Like kvm-ioctls, this crate only provides common APIs and does not provide the end functionalities. Other VFIO crates should use this crate to add specific VFIO implementation support, one example is vfio-pci.

**Comment by chao-p** [comment]
We implemented this and vfio-pci support in cloud-hypervisor (https://github.com/intel/cloud-hypervisor/tree/master/vfio) and want to push everything there except vfio_pci.rs to this crate. We expect some changes to make the code more generic.

**Comment by sameo** [comment]
> Other VFIO crates should use this crate to add specific VFIO implementation support, one example is vfio-pci.

One obvious consumer of the `vfio-ioctls` crate would be the PCI based VFIO implementation. I think the `vfio` crate should contain all bus specific implementations (PCI, platform/MMIO, etc). Each bus support could be disabled through a feature.

So we'd end up with 3 VFIO related crates:

1. `vfio-bindings` for the kernel VFIO API bindings.
2. `vfio-ioctls` for the safe wrappers over the VFIO bindings.
3. `vfio` for providing bus specific implementations to create and expose VFIO devices into rust-vmm guests.

**Comment by jiangliu** [comment]
> > Other VFIO crates should use this crate to add specific VFIO implementation support, one example is vfio-pci.
> 
> One obvious consumer of the `vfio-ioctls` crate would be the PCI based VFIO implementation. I think the `vfio` crate should contain all bus specific implementations (PCI, platform/MMIO, etc). Each bus support could be disabled through a feature.
> 
> So we'd end up with 3 VFIO related crates:
> 
> 1. `vfio-bindings` for the kernel VFIO API bindings.
> 2. `vfio-ioctls` for the safe wrappers over the VFIO bindings.
> 3. `vfio` for providing bus specific implementations to create and expose VFIO devices into rust-vmm guests.

I totally agree with 1 and 2, but have some concerns about 3.
For example, VFIO devices(maybe PCI or mdev devices) may be used to support PCI device passthrough and Virtio MMIO device passthrough. Instead of a vfio crate to implement both PCI and MMIO device passthrough, I think it may be better to split them into PCI crate and virtio crate.

**Comment by sameo** [comment]
> For example, VFIO devices(maybe PCI or mdev devices) may be used to support PCI device passthrough and Virtio MMIO device passthrough. Instead of a vfio crate to implement both PCI and MMIO device passthrough, I think it may be better to split them into PCI crate and virtio crate.

That's another, orthogonal way to do it. I'm not opposed to it, but what would it bring compared to having a vfio crate for it? With the former you bring a VFIO dependency into both the PCI and virtio crate. The latter builds the dependency tree the other way around: PCI and virtio become a vfio dependency.

**Comment by sameo** [comment]
And it seems we're in agreement with creating the `vfio-ioctls` and `vfio-bindings` crates. So I'm all for creating them.

@andreeaflorescu are you also fine with that?

**Comment by jiangliu** [comment]
> And it seems we're in agreement with creating the `vfio-ioctls` and `vfio-bindings` crates. So I'm all for creating them.
> 
> @andreeaflorescu are you also fine with that?

Deal:)
Actually I have drafted the vfio-ioctls crate based on code from cloud hypervisor.
The main change is to support multiple groups per container, multiple device per group:)

**Comment by sameo** [comment]
> The main change is to support multiple groups per container, multiple device per group:)

Sounds good. I assume you're talking about vfio/src/vfio_device.rs? Are you also adding unit tests? Do you need help with that?

**Comment by jiangliu** [comment]
Yes, we have copied vfio_device.rs and vfio_ioctls.rs from cloudhypervisor and then made changes to vfio_device.rs. We are thinking about unit tests too, but it's a little hard because it has dependency on PCI hardware. Any good suggestions for unit and CI tests?

**Comment by chao-p** [comment]
Any objection to create this and #74 ?

**Comment by sameo** [comment]
> Any objection to create this and #74 ?

I'm ok with both.

**Comment by jiangliu** [comment]
I'm OK with both:)

**Comment by sameo** [comment]
Done, closing that issue.
