### ISSUE TITLE
The slack invite link is no longer active

### ISSUE THREAD

**Issue by kangxiaoning** [rust-vmm/community#78]
The slack invite link `Slack: http://bit.ly/rust-vmm-slack` is no longer active.

**Comment by sameo** [comment]
The link on the README is https://tinyurl.com/yyxm3rjh
It seems to work for me, could you please double check?

**Comment by dizz** [comment]
Doesn’t work here 😬

**Comment by andreeaflorescu** [comment]
Yap, it doesn't work if you aren't already registered in the slack channel. Will update it with a permanent one.

**Comment by dizz** [comment]
Cool! Thanks 😎

**Comment by andreeaflorescu** [comment]
Fixed by: https://github.com/rust-vmm/community/pull/79
