### ISSUE TITLE
Crate Addition Request

### ISSUE THREAD

**Issue by npmccallum** [rust-vmm/community#80]
## Crate Name
`kvm`

## Short Description
`rust-vmm` has taken ownership of https://crates.io/crates/kvm. We are going to use this repo for the Lovingly Crafted Interface to replace `kvm-bindings`.

## Why is this crate relevant to the rust-vmm project?

Lovingly Crafted Interfaces will improve overall logical safety and make serialization of the types simpler.

**Comment by andreeaflorescu** [comment]
Repository crated: https://github.com/rust-vmm/kvm
