### ISSUE TITLE
Access Request to rust-vmm

### ISSUE THREAD

**Issue by wxdublin** [rust-vmm/community#88]
This is Wei Xu (https://www.linkedin.com/in/wei-xu-9138471/) from ByteDance Silicon Valley Infrastructure Lab. I am a virtualization veteran, for example, I was the architect of Fireeye MacOS sandbox engine based on KVM and Qemu. I am responsible for the next generation virtualization of ByteDance and so would like to actively participate in the Rust-VMM open source and make contributions to the community.

**Comment by andreeaflorescu** [comment]
Hey Wei Xu, glad to have you here! Contributions to rust-vmm are open to everyone, you do not need any special access. Let us know if you need help with anything. Besides the community repo, if you want to get in touch with the rust-vmm community, you can ping us on Slack or write an email to rust-vmm@lists.opendev.org.
