### ISSUE TITLE
Access Request to rust-vmm

### ISSUE THREAD

**Issue by NotBad4U** [rust-vmm/community#9]
GitHub Username: @NotBad4U
Hello :smile:,
I met @sameo during a Rust meetup and he mentioned the rust-vmm project. I would like to help on this project but I would need a bit of mentoring / pointing for `KVM/Virt` API stuff.
Currently, I'm a system developer at [CleverCloud](https://github.com/CleverCloud), where I use Rust as main language. I'm a contributor on [sozu](https://github.com/sozu-proxy/sozu) (reverse proxy in Rust) and soon `serde` (I have to finish my PR).

**Comment by andreeaflorescu** [comment]
Hey, I sent an invitation. We also have a [slack channel](https://join.slack.com/t/rust-vmm/shared_invite/enQtNTI3NDM2NjA5MzMzLTJiZjUxOGEwMTJkZDVkYTcxYjhjMWU3YzVhOGQ0M2Y5NmU5MzExMjg5NGE3NjlmNzNhZDlhMmY4ZjVhYTQ4ZmQ) that you can join.

I am not sure what are the best resources available for understanding KVM or Virt APIs. For me it works better if I read the code. You can take a look at the following projects:
- [kvmtool](https://git.kernel.org/pub/scm/linux/kernel/git/will/kvmtool.git/about/)
- [CrosVM](https://chromium.googlesource.com/chromiumos/platform/crosvm/)
- [Firecracker](https://github.com/firecracker-microvm/firecracker)

There is also this [article](https://lwn.net/Articles/658511/) that provides an introduction to the KVM API.

I am leaving this issue open in case some other people have any other resources available.

**Comment by NotBad4U** [comment]
Thanks !

**Comment by sameo** [comment]
@NotBad4U is now a member, closing the issue.
